PetWorld/Controllers/AdoptionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PetWorld.Attributes;
using PetWorld.Core.Constants;
using PetWorld.Core.Contracts;
using PetWorld.Core.Models;
using PetWorld.Core.Models.Adoption;
using System.Security.Claims;

namespace PetWorld.Controllers
{
    public class AdoptionController : BaseController
    {
        private readonly IAdoptionService adoptionService;

        private readonly IAgentService agentService;

        public AdoptionController(
            IAdoptionService _adoptionService,
            IAgentService agentService)
        {
            adoptionService = _adoptionService;
            this.agentService = agentService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllAdoptionsQueryModel model)
        {
            var adoptionPets = await adoptionService.AllAsync(
                model.Species,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.AdoptionPetsPerPage);

            model.TotalAdoptionPetsCount = adoptionPets.TotalAdoptionPetsCount;
            model.Adoptions = adoptionPets.AdoptionPets;
            model.SpeciesList = await adoptionService.AllSpeciesNamesAsync();

            var totalPages = (int)Math.Ceiling((double)model.TotalAdoptionPetsCount / model.AdoptionPetsPerPage);
            var аllAdoptionsQueryModel = new AllAdoptionsQueryModel
            {
                CurrentPage = model.CurrentPage,
                TotalPages = totalPages,
                HasPreviousPage = model.CurrentPage > 1,
                HasNextPage = model.CurrentPage < totalPages
            };

            ViewBag.PaginationViewModel = аllAdoptionsQueryModel;


            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Adopt(int id)
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            bool isPetOwner = await adoptionService.IsPetOwnerAsync(userId);

            if (isPetOwner)
            {
                 var adoptionAnimal = await adoptionService.GetAdoptionAnimalByIdAsync(id);

                await adoptionService.AdoptAsync(id, userId, null);

                TempData[MessageConstants.UserMessageSuccess] = "You have successfully adopted the pet! We will call you soon!";

                return RedirectToAction(nameof(All));
            }
            else
            {
                return View(nameof(ProvideOwnerDetails), new PetOwnerFormModel { AdoptionId = id });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Adopt(int id, PetOwnerFormModel petOwnerModel)
        {
            if (await adoptionService.IsAdoptedAsync(id))
            {
                return BadRequest("The pet has already been adopted.");
            }

            if (!ModelState.IsValid)
            {
                return View(petOwnerModel);
            }

            await adoptionService.AdoptAsync(id, User.Id(), petOwnerModel);

            TempData[MessageConstants.UserMessageSuccess] = "You have successfully adopted the pet! We will call you soon!";

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> ProvideOwnerDetails(int adoptionId, PetOwnerFormModel petOwnerModel)
        {
            if (!ModelState.IsValid)
            {
                return View(petOwnerModel);
            }

            await adoptionService.AdoptAsync(adoptionId, User.Id(), petOwnerModel);

            TempData[MessageConstants.UserMessageSuccess] = "You have successfully adopted the pet! We will call you soon!";

            return RedirectToAction(nameof(All));
        }



        [HttpGet]
        [MustBeAgent]
        public async Task<IActionResult> Add()
        {
            var model = new AdoptionFormModel()
            {
                AllSpecies = await adoptionService.AllSpeciesAsync()
            };

            return View(model);
        }

        [HttpPost]
        [MustBeAgent]
        public async Task<IActionResult> Add(AdoptionFormModel model)
        {
            if (ModelState.IsValid == false)
            {
                model.AllSpecies = await adoptionService.AllSpeciesAsync();

                return View(model);
            }

            int? agentId = await agentService.GetAgentIdAsync(User.Id());

            int newAdoptionId = await adoptionService.CreateAsync(model, agentId ?? 0);

            return RedirectToAction(nameof(Details), new { id = newAdoptionId, /*information = model.GetInformation()*/ });
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await adoptionService.SpeciesExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await adoptionService.AdoptionDetailsByIdAsync(id);

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await adoptionService.HasAgentWithIdAsync(id, User.Id()) == false)
            //&& User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var model = await adoptionService.GetAdoptionFormModelByIdAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AdoptionFormModel model)
        {
            if (await adoptionService.SpeciesExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await adoptionService.HasAgentWithIdAsync(id, User.Id()) == false)
            //      && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid == false)
            {
                model.AllSpecies = await adoptionService.AllSpeciesAsync();

                return View(model);
            }

            await adoptionService.EditAsync(id, model);

            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await adoptionService.SpeciesExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await adoptionService.HasAgentWithIdAsync(id, User.Id()) == false)
            //  && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var adoption = await adoptionService.AdoptionDetailsByIdAsync(id);

            var model = new AdoptionDetailsViewModel()
            {
                Id = adoption.Id,
                City = adoption.City,
                ImageUrl = adoption.ImageUrl,
                Name = adoption.Name
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(AdoptionDetailsViewModel model)
        {
            if (await adoptionService.SpeciesExistsAsync(model.Id) == false)
            {
                return BadRequest();
            }

            if (await adoptionService.HasAgentWithIdAsync(model.Id, User.Id()) == false)
            //  && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            await adoptionService.DeleteAsync(model.Id);

            return RedirectToAction(nameof(All));
        }

    }
}

PetWorld/Views/Shared/_AdoptionFormPartial.cshtml
@model AdoptionFormModel

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City"></label>
                <input asp-for="City" class="form-control" placeholder="City...">
                <span asp-validation-for="City" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="It's possible to include the breed of the animal..."></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your fine URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeciesId"></label>
                <select asp-for="SpeciesId" class="form-control">
                    @foreach (var category in Model.AllSpecies)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="SpeciesId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

PetWorld/Views/Shared/_AdoptionPartial.cshtml
@model AdoptionServiceModel
@inject IAdoptionService adoptionService
@inject IAgentService agentService

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Pet Image">
        <div class="card-body text-center">
            <h4>@Model.Name</h4>
            <h6>City: <b>@Model.City</b></h6>

            <a asp-controller="Adoption" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Details</a>
            @if (this.User.Identity.IsAuthenticated)
            {
                <a asp-controller="Adoption" asp-action="Edit" asp-route-id="@Model.Id"
                   class="btn btn-warning">Edit</a>
                <a asp-controller="Adoption" asp-action="Delete" asp-route-id="@Model.Id"
                   class="btn btn-danger">Delete</a>
                <p></p>
            }
            <a asp-controller="Adoption" asp-action="Adopt" asp-route-id="@Model.Id"
               class="btn btn-success">Adopt</a>
        </div>
    </div>
</div>

PetWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetWorld</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetWorld.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetWorld</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(MainMenuComponent))
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - PetWorld
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PetWorld/Views/Shared/_PetFormPartial.cshtml
@model PetFormModel

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" placeholder="Name...">
                <span asp-validation-for="Name" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City"></label>
                <input asp-for="City" class="form-control" placeholder="City...">
                <span asp-validation-for="City" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="It's possible to include the breed of the animal..."></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your fine URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeciesId"></label>
                <select asp-for="SpeciesId" class="form-control">
                    @foreach (var category in Model.AllSpecies)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="SpeciesId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>