PetWorld/Controllers/HotelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetWorld.Attributes;
using PetWorld.Core.Contracts;
using PetWorld.Core.Models.Adoption;
using PetWorld.Core.Models.Hotel;
using PetWorld.Core.Services;
using PetWorld.Infrastructure.Common;
using PetWorld.Infrastructure.Data.Models;
using System.Security.Claims;

namespace PetWorld.Controllers
{
    public class HotelController : BaseController
    {
        private readonly IHotelService hotelService;

        private readonly IAgentService agentService;

        private readonly IRepository repository;

        public HotelController(
            IHotelService _hotelService, IAgentService agentService, IRepository repository)
        {
            hotelService = _hotelService;
            this.agentService = agentService;
            this.repository = repository;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllHotelRoomsQueryModel model)
        {
            var hotelRoom = await hotelService.AllAsync(
                model.RoomType,
                model.CheckInDate,
                model.CheckOutDate);

            if (hotelRoom != null)
            {
                model.HotelRooms = new List<HotelRoomServiceModel> { hotelRoom };
                model.TotalHotelRoomsCount = 1;
            }
            else
            {
                model.HotelRooms = new List<HotelRoomServiceModel>();
                model.TotalHotelRoomsCount = 0;
            }

            model.RoomTypes = await hotelService.AllRoomTypeNamesAsync();

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Reserve(int roomId, DateTime checkInDate, DateTime checkOutDate, bool includesFood, bool includesWalk)
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            var userId = userIdClaim?.Value;

            await hotelService.ReserveRoomAsync(roomId, checkInDate, checkOutDate, includesFood, includesWalk, userId);

            TempData["SuccessMessage"] = "Reservation made successfully !";

            return RedirectToAction("All");
        }

        [HttpGet]
        [MustBeAgent]
        public async Task<IActionResult> Add()
        {
            var model = new HotelRoomFormModel()
            {
                AllRoomTypes = await hotelService.AllRoomTypesAsync()
            };

            return View(model);
        }

        [HttpPost]
        [MustBeAgent]
        public async Task<IActionResult> Add(HotelRoomFormModel model)
        {
            if (ModelState.IsValid == false)
            {
                model.AllRoomTypes = await hotelService.AllRoomTypesAsync();

                return View(model);
            }

            int? agentId = await agentService.GetAgentIdAsync(User.Id());

            int newhotelRoomId = await hotelService.CreateAsync(model, agentId ?? 0);

            TempData["SuccessMessage"] = "Successfully added a new room!";

            return RedirectToAction(nameof(All), new { id = newhotelRoomId, /*information = model.GetInformation()*/ });
        }

        [HttpGet]
        public async Task<IActionResult> Delete()
        {
            var rooms = await hotelService.GetAllRoomsAsync();

            return View(rooms);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, HotelRoomServiceModel model)
        {
            await hotelService.DeleteAsync(model.Id);

            return RedirectToAction("Details");
        }

    }
}

PetWorld/Views/Hotel/Add.cshtml
@model HotelRoomFormModel

@{
    ViewData["Title"] = "Add new hotel room";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />


<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
    <form method="post">
        <div class="form-group">
            <label asp-for="RoomTypeId"></label>
            <select asp-for="RoomTypeId" class="form-control">
                @foreach (var roomType in Model.AllRoomTypes)
                {
                    <option value="@roomType.Id">@roomType.Name</option>
                }
            </select>
            <span asp-validation-for="RoomTypeId" class="small text-danger"></span>
        </div>

        <div class="text-center">
            <input class="btn btn-primary mt-3" type="submit" value="Save" />
        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PetWorld/Views/Hotel/All.cshtml
@model AllHotelRoomsQueryModel

@{
    ViewData["Title"] = "Hotel Rooms";
}

<h2>Here you can book a room</h2>

<div class="d-flex justify-content-end mb-3">
    <a href="@Url.Action("Add", "Hotel")" class="btn btn-primary">Add Room</a>
</div>

<div class="d-flex justify-content-end mb-3">
    <a href="@Url.Action("Delete", "Hotel")" class="btn btn-primary">Delete Room</a>
</div>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<form method="get" asp-action="All">
    <div class="form-group">
        <label asp-for="RoomType">Room Type:</label>
        <select asp-for="RoomType" class="form-control">
            <option value="">All </option>
            @foreach (var roomType in Model.RoomTypes)
            {
                <option value="@roomType">@roomType</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label asp-for="CheckInDate">Check-in Date:</label>
        <input asp-for="CheckInDate" class="form-control" type="date" />
    </div>
    <div class="form-group">
        <label asp-for="CheckOutDate">Check-out Date:</label>
        <input asp-for="CheckOutDate" class="form-control" type="date" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

<div>
    @if (Model.CheckInDate.HasValue && Model.CheckOutDate.HasValue && !string.IsNullOrWhiteSpace(Model.RoomType))
    {
        <h3>Hotel Rooms:</h3>
        @if (Model.HotelRooms.Any())
        {
            <ul class="list-group">
                @foreach (var room in Model.HotelRooms)
                {
                    <li class="list-group-item">
                        <div>
                            <h4>Room: @room.Id</h4>

                             <form method="get" asp-action="Reserve" asp-controller="Hotel">
                                    <input type="hidden" name="roomId" value="@room.Id" />
                                    <input type="hidden" name="checkInDate" value="@Model.CheckInDate?.ToString("yyyy-MM-dd")" />
                                    <input type="hidden" name="checkOutDate" value="@Model.CheckOutDate?.ToString("yyyy-MM-dd")" />

                                    <div>
                                        <label for="includesFood">Includes Food:</label>
                                        <input type="checkbox" id="includesFood" name="includesFood" value="true" />
                                    </div>
                                    <div>
                                        <label for="includesWalk">Includes Walk:</label>
                                        <input type="checkbox" id="includesWalk" name="includesWalk" value="true" />
                                    </div>

                                    <button type="submit" class="btn btn-success">Reserve</button>
                                </form>
                           
                        </div>
                    </li>
                }
            </ul>
        }
        else
        {
            <p>No rooms available for the selected filters.</p>
        }
    }
    else
    {
        <p>Please enter your search criteria above to see available hotel rooms.</p>
    }

PetWorld/Views/Hotel/Delete.cshtml
@model HotelRoomFormModel

@{
    ViewData["Title"] = "Delete hotel room";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}